title: Retro Pastel
description: "Retro Pastel is Jekyll theme made to resemble an old terminal with glowing pastel colors as accents."
encoding: utf-8

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]